<script setup lang="ts">

</script>

<template>
  <div class="
    animated
    animated-bounce
    animated-flash
    animated-pulse
    animated-rubber-band
    animated-shake-x
    animated-shake-y
    animated-head-shake
    animated-swing
    animated-tada
    animated-wobble
    animated-jello
    animated-heart-beat
    animated-back-in-down
    animated-back-in-left
    animated-back-in-right
    animated-back-in-up
    animated-back-out-down
    animated-back-out-left
    animated-back-out-right
    animated-back-out-up
    animated-bounce-in
    animated-bounce-in-down
    animated-bounce-in-left
    animated-bounce-in-right
    animated-bounce-in-bounce-in-up
    animated-bounce-out
    animated-bounce-out-down
    animated-bounce-out-left
    animated-bounce-out-right
    animated-bounce-out-bounce-in-up
    animated-fade-in
    animated-fade-in-down
    animated-fade-in-down-big
    animated-fade-in-left
    animated-fade-in-left-big
    animated-fade-in-right
    animated-fade-in-right-big
    animated-fade-in-up
    animated-fade-in-up-big
    animated-fade-in-top-left
    animated-fade-in-top-right
    animated-fade-in-bottom-left
    animated-fade-in-bottom-right
    animated-fade-out
    animated-fade-out-down
    animated-fade-out-down-big
    animated-fade-out-left
    animated-fade-out-left-big
    animated-fade-out-right
    animated-fade-out-right-big
    animated-fade-out-up
    animated-fade-out-up-big
    animated-fade-out-top-left
    animated-fade-out-top-right
    animated-fade-out-bottom-left
    animated-fade-out-bottom-right
    animated-flip
    animated-flip-in-x
    animated-flip-in-y
    animated-flip-out-x
    animated-flip-out-y
    animated-light-speed-in-right
    animated-light-speed-in-left
    animated-light-speed-out-right
    animated-light-speed-out-left
    animated-rotate-in
    animated-rotate-in-down-left
    animated-rotate-in-down-right
    animated-rotate-in-up-left
    animated-rotate-in-up-right
    animated-rotate-out
    animated-rotate-out-down-left
    animated-rotate-out-down-right
    animated-rotate-out-up-left
    animated-rotate-out-up-right
    animated-hinge
    animated-jack-in-the-box
    animated-roll-in
    animated-roll-out
    animated-zoom-in
    animated-zoom-in-down
    animated-zoom-in-left
    animated-zoom-in-right
    animated-zoom-in-up
    animated-zoom-out
    animated-zoom-out-down
    animated-zoom-out-left
    animated-zoom-out-right
    animated-zoom-out-up
    animated-slide-in-down
    animated-slide-in-left
    animated-slide-in-right
    animated-slide-in-up
    animated-slide-out-down
    animated-slide-out-left
    animated-slide-out-right
    animated-slide-out-up
    "
  />
</template>
