/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Animated: typeof import('./components/Animated.vue')['default']
    Demo: typeof import('./components/Demo.vue')['default']
  }
}
