name: Pull Test

on:
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - name: pnpm Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run core
      - name: Coveralls
        run: pnpm run coverage

  vue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run core
      - name: Test
        run: pnpm run test

  docs-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run core
      - name: Docs Build
        run: pnpm run docs:build
